=== AndyHowlettGitHub/cdk/changelog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns="http://cdk.sf.net/schema/changelog"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://cdk.sf.net/schema/changelog"
  elementFormDefault="qualified">

   <xsd:attributeGroup name="changeGrp">
     <xsd:attribute name="contributor" type="contributorListType" default="unknown"/>
     <xsd:attribute name="date" type="xsd:date" use="optional"/>
   </xsd:attributeGroup>

  <xsd:simpleType name="contributorType">
    <xsd:restriction base="xsd:string">
      <!-- This is a alphabetical list of contributors to CDK.
           The id's used are (if possible) the SF accounts. -->
      
      <xsd:enumeration value="chhoppe"/>        <!-- Christian Hoppe <c.hoppe_@web.de> -->
      <xsd:enumeration value="cpudney"/>    <!-- Chris Pudney <cpudney@users.sf.net> -->
      <xsd:enumeration value="egonw"/>      <!-- Egon Willighagen <e.willighagen@science.ru.nl> -->
      <xsd:enumeration value="irilenia"/>   <!-- Irilenia Nobeli <nobeli@ebi.ac.uk> -->
      <xsd:enumeration value="meklund"/>    <!-- Martin Eklund <martin.eklund@farmbio.uu.se> -->
      <xsd:enumeration value="shk3"/>       <!-- Stefan Kuhn <stefan.kuhn@uni-koeln.de> -->
      <xsd:enumeration value="steinbeck"/>  <!-- Christoph Steinbeck <c.steinbeck@uni-koeln.de> -->
      <xsd:enumeration value="thanser"/>    <!-- Thierry Hanser <thierry.hanser@ixelis.com> -->
      <xsd:enumeration value="tohel"/>      <!-- Tobias Helmus <tobias.helmus@uni-koeln.de> -->
      <xsd:enumeration value="ulif"/>       <!-- Uli Fechner <u.fechner@chemie.uni-frankfurt.de> -->
      
      
      <!-- Contributor was untracable -->
      <xsd:enumeration value="unknown"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="closesType">
    <xsd:list itemType="xsd:positiveInteger"/>
  </xsd:simpleType>
  
  <xsd:simpleType name="contributorListType">
    <xsd:list itemType="contributorType"/>
  </xsd:simpleType>
  
  <xsd:element name="changelog">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="release" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="release">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:choice>
          <xsd:element ref="addition" />
          <xsd:element ref="bugfix"   />
          <xsd:element ref="apiChange"/>
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="addition">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attributeGroup ref="changeGrp"/>
          <xsd:attribute name="implements" type="closesType" use="optional"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="bugfix">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attributeGroup ref="changeGrp"/>
          <xsd:attribute name="closes" type="closesType" use="optional"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="apiChange">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attributeGroup ref="changeGrp"/>
          <xsd:attribute name="implements" type="closesType" use="optional"/>
          <xsd:attribute name="closes" type="closesType" use="optional"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== AndyHowlettGitHub/cdk/changelog.xml
<?xml version="1.0" encoding="utf-8"?>
<changelog xmlns="http://cdk.sf.net/schema/changelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://cdk.sf.net/schema/changelog changelog.xsd">

  <release id="cvs">
   <bugfix contributor="egonw">
     Fixed reading of SDF files created by common software, as reported
     by a coworker of Uli.
   </bugfix>
   <addition contributor="egonw">
     Added a basic Mol2 writer that outputs atoms and bonds
   </addition>
   <addition contributor="egonw">
     Added option to set the cause of a CDKException.
   </addition>
   <addition contributor="chhoppe">
     removed queryAtomContainer out of XLogP Descriptor see bug 1296383. Add test for aspirin.
   </addition>
   <addition contributor="chhoppe">
     Added a method to find pockets and cavities in BioPolymers, cdk.protein.ProteinPocketFinder()
   </addition>
   <addition contributor="egonw">
     Added getAllChemObjects() methods to the cdk.tools.manipulators
   </addition>
   <addition contributor="egonw">
     Added a cdk.interfaces.ChemObjectBuilder for constructing data classes
     when the implementating package is unknown
   </addition>
   <addition contributor="egonw">
     CMLReader now reuses the passed ChemObject, so that one can have a CML 
     file's content be read into a custom ChemObject
   </addition>
   <apiChange contributor="egonw">
     ChemObjectListener was moved to the cdk.interfaces package
   </apiChange>
   <apiChange contributor="egonw">
     The data classes interfaces now only use interfaces, and cdk-interfaces
     no longer depends on cdk-data
   </apiChange>
   <apiChange contributor="egonw">
     Removed ChemObjectWriter.highestSupportedChemObject() as it depended
     on an implementing data class, and the CDK library did not depend on it
   </apiChange>
   <apiChange contributor="egonw">
     INChIContentProcessor.processConnections() now takes an additional
     cdk.interfaces.AtomContainer as parameter
   </apiChange>
   <apiChange contributor="egonw">
     The AtomTypeFactory and IsotopeFactory now require a ChemObjectBuilder
     to be passed
   </apiChange>
   <apiChange contributor="egonw">
     The constructor MFAnalyser(String) now requires a second parameter being
     an AtomContainer
   </apiChange>
   <apiChange contributor="egonw" implements="1261434">
     The ChemObjectIO interfaces deprecates accepts(ChemObject) in favor of
     the new accepts(Class)
   </apiChange>
  </release>
  
  <release id="20050826">
    <addition contributor="egonw">
      Added a cdk.tools.ProteinBuilderTool to build protein structures
    </addition>
    <addition contributor="egonw">
      Added a AminoAcid class that extends Monomer
    </addition>
    <addition contributor="chhoppe">
      Added MM2AtomTypeMatcher to cdk
    </addition>
    <addition contributor="shk3">
      BondTools contains a method if a double bond configuration is cis or trans
    </addition>
    <addition contributor="shk3 tohel">
      For the embedded component, the menu can be exported and integrated into mparent application
    </addition>
    <addition contributor="shk3 tohel">
      Embedded component has own context menu with file related functions
    </addition>
    <addition contributor="shk3 tohel">
      Drawing area has a defined size, currently only A4
    </addition>
    <addition contributor="shk3 tohel">
      Menu/Tool/Statusbar can be hidden and by hiding all the editor looks like an viewer
    </addition>
    <addition contributor="shk3 tohel">
      When double clicking on embedded drawing panel, new editor/viewer frame pops up with model of exisiting frame
    </addition>
    <addition contributor="shk3 tohel">
      Applets for editor and viewer exist
    </addition>
    <addition contributor="shk3 tohel">
      Splitting of JCP in editor and viewer as separate applications
    </addition>
    <addition contributor="chhoppe">
      Added MMFF94AtomTypeMatcher to cdk
    </addition>
    <apiChange closes="1208740">
      Deprecated RTools which should be removed in the first release after the
      next; it's outdated, contains a few bugs, and redundant. Use 
      UniversalIsomorphismTester instead.
    </apiChange>
    <bugfix contributor="irilenia thanser" closes="1208740">
      Fixed copying and matching of aromatic bonds.
    </bugfix>
    <bugfix contributor="meklund" closes="1193703">
      Fixed broken Junit test when coffein.pdb is read. Corrected way of setting
      element symbol in PDBAtom.
    </bugfix>
    <addition contributor="egonw">
      Added an option for flipping a selected molecule horizontally or vertically.
    </addition>
    <addition contributor="egonw">
      Insert from SMILES in JChemPaint now really inserts, instead of adding a new
      model.
    </addition>
    <addition contributor="egonw">
      Added copy/paste functionality to JChemPaint.
    </addition>
    <addition contributor="steinbeck">
      Added classes for permuting the order of atoms in an AtomContainer 
      (graph.AtomContainerAtomPermutor)
    </addition>
    <addition>
      AtomPlacer now draws 180 deg geometry when encountering triple bonds
    </addition>
    <addition contributor="steinbeck">
      JChemPaint sources reintegrated to applications.jchempaint package
    </addition>
    <addition>
      Added new method MFAnalyser.getHTMLMolecularFormulaWithCharge()
    </addition>
    <addition>
      Added new methods SetOfAtomContainers.removeAtomContainer()
    </addition>
    <addition>
      Added a CDKRXNWriter.
    </addition>
    <addition contributor="egonw" implements="1062516">
      Atom type list for PDB atom codes
    </addition>
    <addition contributor="egonw" implements="824133">
      Implemented an iterating (event based) CML reader
    </addition>
    <addition contributor="egonw">
      ReaderFactory now uses the new CDK set io-formats instead of
      hardcoding the recognized formats
    </addition>
    <addition contributor="egonw" implements="954356">
      The PluginManager now adds the plugin menu to the plugin window
    </addition>
    <addition contributor="egonw">
      Jmol API and IO from CVS HEAD on 10.05
    </addition>
    <addition contributor="meklund">
      Added AminoAcid templates
    </addition>
    <addition>
      The libio.cml.Convertor now also accepts AtomContainer
    </addition>
    <addition implements="949751">
      Added customization of atom color for Renderer[2D|3D]Model
    </addition>
    <addition contributor="egonw">
      Added the new method CDKPluginInterface.getPluginLicense()
    </addition>
    <addition contributor="egonw">
      Added the new method CDKEditBus.runScript()
    </addition>
    <addition contributor="egonw">
      CML2 from Jumbo 4.6 was uploaded (for Java 1.4 and 1.5)
    </addition>
    <addition contributor="egonw">
      Added rendering of radicals (SingleElectron)
    </addition>
    <addition contributor="egonw">
      Added reading of 'M  RAD' from MDL molfiles
    </addition>
    <addition contributor="egonw">
      Added writing and reading of radicals in CML2
    </addition>
    <addition>
      Added getRelevantAtomContainer(ChemObject, Bond) to cdk.tools.manipulators
    </addition>
    <addition contributor="egonw" implements="1177112">
      Implemented reading of data items from MDL SD files
    </addition>
    <addition contributor="egonw">
      Added cdk.index.CASNumber.calculateCheckBit()
    </addition>
    <addition contributor="egonw">
      Added the new class PDBAtom with field for PDB specific information
    </addition>
    <addition contributor="egonw">
      Added a CML Customizer interface which reduces the CDK module dependency
      of the libio-cml module
    </addition>
    <addition contributor="egonw">
      Added two new module for outputting data for specific CDK modules:
      pdb-cml for outputing PDBAtom information, and qsar-cml for outputing
      QSAR-descriptor information
    </addition>
    <bugfix contributor="egonw" closes="1260766">
      Removed exponential growth of the ChemSequence length.
    </bugfix>
    <bugfix contributor="ulif" closes="1212219">
      Fixed output of mass number information in MDL files.
    </bugfix>
    <bugfix contributor="thanser" closes="1110537 999330">
      Fixed problem with UniversalIsomorphism. Under certain conditions extra subgraphs
      were found, breaking symmetry.
    </bugfix>
    <bugfix>
      Fixed KabschAlignment so that the rotation matrixi, U, is returned properly
    </bugfix>
    <bugfix>
      Fixed junit-test and run-test: missing cdk-data.jar
    </bugfix>
    <bugfix>
      Don't consume Exceptions while writing MDL
    </bugfix>
    <bugfix closes="1118689">
      Removed entry for 'D' in the isotope list; '2H' is still present
    </bugfix>
    <bugfix>
      Fail more informative on (corrupt) MDL files that lack the property block
    </bugfix>
    <bugfix contributor="egonw">
      Fixed API detection in CDKPluginManager when distributing change events
    </bugfix>
    <bugfix>
      Fixed returning of SingleElectron's with AtomContainer
      .getConnectedElectronContainers(Atom)
    </bugfix>
    <bugfix>
      Fixed retaining LonePair's and SingleElectron's when using
      ConnectivityChecker.partitionIntoMolecules()
    </bugfix>
    <bugfix>
      Fixed showing ElectronContainers in the cdk.apps.swing.ChemObectTree
    </bugfix>
    <bugfix contributor="egonw" closes="1172425">
      The IteratingMDLReader can now also read MDL molfiles with only one
      molecule
    </bugfix>
    <bugfix>
      Fixed output of CML2 for reactions with IDs
    </bugfix>
    <bugfix closes="1169385" contributor="egonw">
      CDK IO is now fully supports InputStream
    </bugfix>
    <bugfix closes="1185991">
      Fixed error in isotope list
    </bugfix>
    <bugfix>
      Fixed reading of Z from CrystClust files
    </bugfix>
